CREATE TABLE motos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa         VARCHAR(10),
    modelo        VARCHAR(50),
    numero_chassi VARCHAR(17),
    status        VARCHAR(255)                            NOT NULL,
    usuario_id    BIGINT,
    CONSTRAINT pk_moto PRIMARY KEY (id)
);

CREATE TABLE userss
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(100),
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES users (id);